# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  release:
    types: ["published"]

env:
  CTX_ENVIRONMENT: 'staging'
jobs:
  setDeployEnv:
    name: 'Set Deployment Environment'
    runs-on: [self-hosted, linux]
    env:
      deploy: staging
    outputs:
      deploy_env: ${{ env.deploy }}
    steps:
    - name: Determine Environment
      run: |
          if [[ ${{ GITHUB.EVENT_NAME }} = "push" ]]; then
              echo "deploy=Staging" >> $GITHUB_ENV
          elif [[ ${{ GITHUB.EVENT_NAME }} = "publish" ]]; then
              echo "deploy=Production" >> $GITHUB_ENV
          else
              echo "deploy=NONE" >> $GITHUB_ENV
          fi
          echo "Deploying to ${{ env.deploy }} from branch ${{ GITHUB.REF }}"

  build:
    needs: setDeployEnv
    runs-on: ubuntu-latest
    environment: 
        name: ${{ needs.setDeployEnv.outputs.deploy_env }}
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo $GITHUB.EVENT_NAME - ${{ needs.setDeployEnv.outputs.deploy_env }}
