# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      gitCommitID:
        description: Github (SHA) Commit ID
        default: "please put your commit id"
        required: true

env:
  CTX_ENVIRONMENT: 'staging'
jobs:
  build:
    if: ${{ github.event.name == 'workflow_dispatch' && success() }}
    env:
      CTX_ENVIRONMENT: 'production'
    runs-on: ubuntu-latest
    environment: ${{env.CTX_ENVIRONMENT}}
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "$GITHUB_EVENT_NAME - $CTX_ENVIRONMENT - ${{ vars.VAR_NAME }}"
